# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T10:00:39+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union
from uuid import UUID

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity

from models import (
    AdditionalTaxIdentifier,
    AdditionalTaxIdentifierCreate,
    AdditionalTaxIdentifierUpdate,
    Administration,
    AdministrationCreate,
    AdministrationUpdate,
    CountrySpecifications,
    DiscoverableParticipant,
    DiscoveredParticipant,
    DiscoveryExistsPostResponse,
    DiscoveryReceivesPostResponse,
    DocumentSubmission,
    DocumentSubmissionEvidence,
    DocumentSubmissionResult,
    DocumentSubmissionsPostResponse,
    EvidenceType,
    InvoiceRecipientPreflight,
    InvoiceSubmission,
    InvoiceSubmissionEvidence,
    InvoiceSubmissionResult,
    InvoiceSubmissionsPostResponse,
    InvoiceSubmissionsPreflightPostResponse,
    LegalEntitiesIdPatchResponse,
    LegalEntitiesLegalEntityIdAdditionalTaxIdentifiersPostResponse,
    LegalEntitiesLegalEntityIdAdministrationsPostResponse,
    LegalEntitiesLegalEntityIdPeppolIdentifiersPostResponse,
    LegalEntitiesLegalEntityIdReceivedDocumentsPostResponse,
    LegalEntitiesPostResponse,
    LegalEntity,
    LegalEntityCreate,
    LegalEntityUpdate,
    PackageVersion3,
    Packaging3,
    Packaging4,
    PeppolIdentifier,
    PeppolIdentifierCreate,
    PreflightInvoiceRecipientResult,
    PurchaseInvoice,
    PurchaseInvoiceUbl,
    ReceivedDocument,
    ReceivedDocumentCreate,
    ReceivedDocumentsPostResponse,
    Syntax,
    WebhookInstance,
)

app = MCPProxy(
    contact={'email': 'apisupport@storecove.nl'},
    description='Storecove API',
    title='Storecove API',
    version='2.0.1',
    servers=[{'url': 'https://api.storecove.com/api/v2'}],
)


@app.post(
    '/discovery/exists',
    description=""" Discover if a network participant exists. """,
    tags=['network_discovery_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def discovery_exists(body: DiscoverableParticipant):
    """
    Discover Network Participant Existence
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/discovery/identifiers',
    description=""" Discover the identifiers used in each country, for routing, for legal identification as well as for tax identification purposes. We are currently testing this endpoint with selected Customers. If you would like to participate, please contact us. """,
    tags=[
        'network_discovery_operations',
        'legal_entity_admin_operations',
        'tax_identifier_operations',
    ],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def discovery_identifiers():
    """
    Discover Country Identifiers ** EXPERIMENTAL
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/discovery/receives',
    description=""" Discover a network participant and capabilities. """,
    tags=['network_discovery_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def discovery_receives(body: DiscoverableParticipant):
    """
    Disover Network Participant
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/document_submissions',
    description=""" Submit a document for delivery. This endpoint will replaces the /invoice_submissions endpoint which will soon be deprecated. """,
    tags=['submission_document_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def create_document_submission(body: DocumentSubmission):
    """
    Submit a new document.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/document_submissions/{guid}/evidence/{evidence_type}',
    description=""" Get evidence for a DocumentSubmission by GUID with corresponding status """,
    tags=['submission_document_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def show_document_submission_evidence(
    guid: UUID, evidence_type: EvidenceType = 'sending'
):
    """
    Get DocumentSubmission Evidence
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/invoice_submissions',
    description=""" DEPRECATED. Use the new /document_submissions endpoint. Submit an invoice for delivery. """,
    tags=['submission_document_management', 'invoice_processing_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def create_invoice_submission(body: InvoiceSubmission):
    """
    Submit a new invoice
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/invoice_submissions/preflight',
    description=""" Deprecated. Use the new /discovery endpoint. Check whether Storecove can deliver an invoice for a list of ids. """,
    tags=['invoice_processing_management', 'submission_document_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def preflight_invoice_recipient(body: InvoiceRecipientPreflight):
    """
    DEPRECATED. Preflight an invoice recipient
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/invoice_submissions/{guid}/evidence',
    description=""" Deprecated. Use the new /document_submissions/{guid}/evidence endpoint. Get evidence for an InvoiceSubmission by GUID with corresponding status """,
    tags=['submission_document_management', 'invoice_processing_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def show_invoice_submission_evidence(guid: UUID):
    """
    DEPRECATED. Get InvoiceSubmission Evidence
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/legal_entities',
    description=""" Create a new LegalEntity. """,
    tags=['legal_entity_admin_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def create_legal_entity(body: LegalEntityCreate):
    """
    Create a new LegalEntity
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/legal_entities/{id}',
    description=""" Delete a specific LegalEntity. """,
    tags=['legal_entity_admin_operations', 'administration_entity_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def delete_legal_entity(id: int):
    """
    Delete LegalEntity
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/legal_entities/{id}',
    description=""" Get a specific LegalEntity. """,
    tags=['legal_entity_admin_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def get_legal_entity(id: int):
    """
    Get LegalEntity
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/legal_entities/{id}',
    description=""" Update a specific LegalEntity. """,
    tags=['legal_entity_admin_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def update_legal_entity(id: int, body: LegalEntityUpdate = ...):
    """
    Update LegalEntity
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/legal_entities/{legal_entity_id}/additional_tax_identifiers',
    description=""" Create a new AdditionalTaxIdentifier. An AdditionalTaxIdentifier is a seconday tax identifier that is used inside the EU when sending invoices to consumers. In that case, the VAT of the receiving country is used and if the sender has a local VAT identifier, that is used to identifiy the sender, instead of the sender's origin country VAT number. To use these identifiers, use the invoice.consumerTaxMode = true property. """,
    tags=['tax_identifier_operations', 'legal_entity_admin_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def create_additional_tax_identifier(
    legal_entity_id: int, body: AdditionalTaxIdentifierCreate = ...
):
    """
    Create a new AdditionalTaxIdentifier
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/legal_entities/{legal_entity_id}/additional_tax_identifiers/{id}',
    description=""" Delete an AdditionalTaxIdentifier """,
    tags=['legal_entity_admin_operations', 'tax_identifier_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def delete_additional_tax_identifier(legal_entity_id: int, id: int = ...):
    """
    Delete AdditionalTaxIdentifier
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/legal_entities/{legal_entity_id}/additional_tax_identifiers/{id}',
    description=""" Get an AdditionalTaxIdentifier """,
    tags=['legal_entity_admin_operations', 'tax_identifier_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def get_additional_tax_identifier(legal_entity_id: int, id: int = ...):
    """
    Get AdditionalTaxIdentifier
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/legal_entities/{legal_entity_id}/additional_tax_identifiers/{id}',
    description=""" Update an AdditionalTaxIdentifier """,
    tags=['legal_entity_admin_operations', 'tax_identifier_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def update_additional_tax_identifier(
    legal_entity_id: int, id: int = ..., body: AdditionalTaxIdentifierUpdate = ...
):
    """
    Update AdditionalTaxIdentifier
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/legal_entities/{legal_entity_id}/administrations',
    description=""" Deprecated. Create a new Administration. An Administration is an email destination for purchase invoices. """,
    tags=['legal_entity_admin_operations', 'administration_entity_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def create_administration(legal_entity_id: int, body: AdministrationCreate = ...):
    """
    Create a new Administration
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/legal_entities/{legal_entity_id}/administrations/{id}',
    description=""" Deprecated. Delete an Administration """,
    tags=['legal_entity_admin_operations', 'administration_entity_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def delete_administration(legal_entity_id: int, id: int = ...):
    """
    Delete Administration
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/legal_entities/{legal_entity_id}/administrations/{id}',
    description=""" Deprecated. Get an Administration """,
    tags=['legal_entity_admin_operations', 'administration_entity_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def get_administration(legal_entity_id: int, id: int = ...):
    """
    Get Administration
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/legal_entities/{legal_entity_id}/administrations/{id}',
    description=""" Deprecated. Update an Administration """,
    tags=['legal_entity_admin_operations', 'administration_entity_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def update_administration(
    legal_entity_id: int, id: int = ..., body: AdministrationUpdate = ...
):
    """
    Update Administration
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/legal_entities/{legal_entity_id}/peppol_identifiers',
    description=""" Create a brand new new PeppolIdentifier. For <<_sg_singapore>>, special rules apply. """,
    tags=['legal_entity_admin_operations', 'network_discovery_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def create_peppol_identifier(legal_entity_id: int, body: PeppolIdentifierCreate = ...):
    """
    Create a new PeppolIdentifier
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/legal_entities/{legal_entity_id}/peppol_identifiers/{superscheme}/{scheme}/{identifier}',
    description=""" Delete a PeppolIdentifier. """,
    tags=['legal_entity_admin_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def delete_peppol_identifier(
    legal_entity_id: int,
    superscheme: str = ...,
    scheme: str = ...,
    identifier: str = ...,
):
    """
    Delete PeppolIdentifier
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/legal_entities/{legal_entity_id}/received_documents',
    description=""" DEPRECATED - use new path /received_documents. Receive a new Document. """,
    tags=['submission_document_management', 'legal_entity_admin_operations'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def receive_documenht(legal_entity_id: int, body: ReceivedDocumentCreate = ...):
    """
    Receive a new Document
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/purchase_invoices/{guid}',
    description=""" Get a specific PurchaseInvoice, in JSON format. """,
    tags=['invoice_processing_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def get_invoice_json(guid: UUID, pmv: Optional[str] = '1.0'):
    """
    Get Purchase invoice data as JSON
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/purchase_invoices/{guid}/{packaging}',
    description=""" Get a specific PurchaseInvoice. """,
    tags=['invoice_processing_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def get_invoice_ubl(
    guid: UUID, packaging: Packaging3 = 'json', pmv: Optional[str] = '1.0'
):
    """
    Get Purchase invoice data in a selectable format
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/purchase_invoices/{guid}/{packaging}/{package_version}',
    description=""" Get a specific PurchaseInvoice in UBL format """,
    tags=['invoice_processing_management', 'submission_document_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def get_invoice_ubl_versioned(
    guid: UUID, packaging: Packaging4 = 'ubl', package_version: PackageVersion3 = 'si11'
):
    """
    Get Purchase invoice data as JSON with a Base64-encoded UBL string in the specified version
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/received_documents',
    description=""" Create a new received document. """,
    tags=['submission_document_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def create_received_document(body: ReceivedDocumentCreate):
    """
    Create a new received document
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/received_documents/{guid}/{format}',
    description=""" EXPERIMENTAL: use only for orders. Get a new ReceivedDocument. """,
    tags=['submission_document_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def get_received_document(guid: UUID, syntax: Syntax = 'json', format: str = ...):
    """
    Get a new ReceivedDocument
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/webhook_instances/',
    description=""" GET a WebhookInstance from the queue. After processing it successfully, DELETE it and GET the next one. When a 204 is received, the queue is empty and the polling process can sleep for a while. """,
    tags=['webhook_service_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def get_webhook_instances():
    """
    GET a WebhookInstance
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/webhook_instances/{guid}',
    description=""" DELETE a specific WebhookInstance """,
    tags=['webhook_service_management'],
    security=[
        APIKeyHeader(name="Authorization"),
    ],
)
def delete_webhook_instance(guid: UUID):
    """
    DELETE a WebhookInstance
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
